#include <open62541/plugin/log_stdout.h>
#include <open62541/server.h>
#include <open62541/server_config_default.h>
#include "build/src_generated/open62541/namespace_Robotics_generated.h"
#include "build/src_generated/open62541/namespace_di_generated.h"
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>


UA_Boolean running = true;

//const char* getErrorName(UA_StatusCode my_error);

static void stopHandler(int sign) {
    UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "received ctrl-c");
    running = false;
}

const char* getErrorName(UA_StatusCode my_error) 
{
   switch (my_error) 
   {
	case UA_STATUSCODE_GOOD: return "UA_STATUSCODE_GOOD";
	case UA_STATUSCODE_BADUNEXPECTEDERROR: return "UA_STATUSCODE_BADUNEXPECTEDERROR";
	case UA_STATUSCODE_BADINTERNALERROR: return "UA_STATUSCODE_BADINTERNALERROR";
	case UA_STATUSCODE_BADOUTOFMEMORY: return "UA_STATUSCODE_BADOUTOFMEMORY";
	case UA_STATUSCODE_BADRESOURCEUNAVAILABLE: return "UA_STATUSCODE_BADRESOURCEUNAVAILABLE";
	case UA_STATUSCODE_BADCOMMUNICATIONERROR: return "UA_STATUSCODE_BADCOMMUNICATIONERROR";
	case UA_STATUSCODE_BADENCODINGERROR: return "UA_STATUSCODE_BADENCODINGERROR";
	case UA_STATUSCODE_BADDECODINGERROR: return "UA_STATUSCODE_BADDECODINGERROR";
	case UA_STATUSCODE_BADENCODINGLIMITSEXCEEDED: return "UA_STATUSCODE_BADENCODINGLIMITSEXCEEDED";
	case UA_STATUSCODE_BADREQUESTTOOLARGE: return "UA_STATUSCODE_BADREQUESTTOOLARGE";
	case UA_STATUSCODE_BADRESPONSETOOLARGE: return "UA_STATUSCODE_BADRESPONSETOOLARGE";
	case UA_STATUSCODE_BADUNKNOWNRESPONSE: return "UA_STATUSCODE_BADUNKNOWNRESPONSE";
	case UA_STATUSCODE_BADTIMEOUT: return "UA_STATUSCODE_BADTIMEOUT";
	case UA_STATUSCODE_BADSERVICEUNSUPPORTED: return "UA_STATUSCODE_BADSERVICEUNSUPPORTED";
	case UA_STATUSCODE_BADSHUTDOWN: return "UA_STATUSCODE_BADSHUTDOWN";
	case UA_STATUSCODE_BADSERVERNOTCONNECTED: return "UA_STATUSCODE_BADSERVERNOTCONNECTED";
	case UA_STATUSCODE_BADSERVERHALTED: return "UA_STATUSCODE_BADSERVERHALTED";
	case UA_STATUSCODE_BADNOTHINGTODO: return "UA_STATUSCODE_BADNOTHINGTODO";
	case UA_STATUSCODE_BADTOOMANYOPERATIONS: return "UA_STATUSCODE_BADTOOMANYOPERATIONS";
	case UA_STATUSCODE_BADTOOMANYMONITOREDITEMS: return "UA_STATUSCODE_BADTOOMANYMONITOREDITEMS";
	case UA_STATUSCODE_BADDATATYPEIDUNKNOWN: return "UA_STATUSCODE_BADDATATYPEIDUNKNOWN";
	case UA_STATUSCODE_BADCERTIFICATEINVALID: return "UA_STATUSCODE_BADCERTIFICATEINVALID";
	case UA_STATUSCODE_BADSECURITYCHECKSFAILED: return "UA_STATUSCODE_BADSECURITYCHECKSFAILED";
	case UA_STATUSCODE_BADCERTIFICATETIMEINVALID: return "UA_STATUSCODE_BADCERTIFICATETIMEINVALID";
	case UA_STATUSCODE_BADCERTIFICATEISSUERTIMEINVALID: return "UA_STATUSCODE_BADCERTIFICATEISSUERTIMEINVALID";
	case UA_STATUSCODE_BADCERTIFICATEHOSTNAMEINVALID: return "UA_STATUSCODE_BADCERTIFICATEHOSTNAMEINVALID";
	case UA_STATUSCODE_BADCERTIFICATEURIINVALID: return "UA_STATUSCODE_BADCERTIFICATEURIINVALID";
	case UA_STATUSCODE_BADCERTIFICATEUSENOTALLOWED: return "UA_STATUSCODE_BADCERTIFICATEUSENOTALLOWED";
	case UA_STATUSCODE_BADCERTIFICATEISSUERUSENOTALLOWED: return "UA_STATUSCODE_BADCERTIFICATEISSUERUSENOTALLOWED";
	case UA_STATUSCODE_BADCERTIFICATEUNTRUSTED: return "UA_STATUSCODE_BADCERTIFICATEUNTRUSTED";
	case UA_STATUSCODE_BADCERTIFICATEREVOCATIONUNKNOWN: return "UA_STATUSCODE_BADCERTIFICATEREVOCATIONUNKNOWN";
	case UA_STATUSCODE_BADCERTIFICATEISSUERREVOCATIONUNKNOWN: return "UA_STATUSCODE_BADCERTIFICATEISSUERREVOCATIONUNKNOWN";
	case UA_STATUSCODE_BADCERTIFICATEREVOKED: return "UA_STATUSCODE_BADCERTIFICATEREVOKED";
	case UA_STATUSCODE_BADCERTIFICATEISSUERREVOKED: return "UA_STATUSCODE_BADCERTIFICATEISSUERREVOKED";
	case UA_STATUSCODE_BADUSERACCESSDENIED: return "UA_STATUSCODE_BADUSERACCESSDENIED";
	case UA_STATUSCODE_BADIDENTITYTOKENINVALID: return "UA_STATUSCODE_BADIDENTITYTOKENINVALID";
	case UA_STATUSCODE_BADIDENTITYTOKENREJECTED: return "UA_STATUSCODE_BADIDENTITYTOKENREJECTED";
	case UA_STATUSCODE_BADSECURECHANNELIDINVALID: return "UA_STATUSCODE_BADSECURECHANNELIDINVALID";
	case UA_STATUSCODE_BADINVALIDTIMESTAMP: return "UA_STATUSCODE_BADINVALIDTIMESTAMP";
	case UA_STATUSCODE_BADNONCEINVALID: return "UA_STATUSCODE_BADNONCEINVALID";
	case UA_STATUSCODE_BADSESSIONIDINVALID: return "UA_STATUSCODE_BADSESSIONIDINVALID";
	case UA_STATUSCODE_BADSESSIONCLOSED: return "UA_STATUSCODE_BADSESSIONCLOSED";
	case UA_STATUSCODE_BADSESSIONNOTACTIVATED: return "UA_STATUSCODE_BADSESSIONNOTACTIVATED";
	case UA_STATUSCODE_BADSUBSCRIPTIONIDINVALID: return "UA_STATUSCODE_BADSUBSCRIPTIONIDINVALID";
	case UA_STATUSCODE_BADREQUESTHEADERINVALID: return "UA_STATUSCODE_BADREQUESTHEADERINVALID";
	case UA_STATUSCODE_BADTIMESTAMPSTORETURNINVALID: return "UA_STATUSCODE_BADTIMESTAMPSTORETURNINVALID";
	case UA_STATUSCODE_BADREQUESTCANCELLEDBYCLIENT: return "UA_STATUSCODE_BADREQUESTCANCELLEDBYCLIENT";
	case UA_STATUSCODE_GOODSUBSCRIPTIONTRANSFERRED: return "UA_STATUSCODE_GOODSUBSCRIPTIONTRANSFERRED";
	case UA_STATUSCODE_GOODCOMPLETESASYNCHRONOUSLY: return "UA_STATUSCODE_GOODCOMPLETESASYNCHRONOUSLY";
	case UA_STATUSCODE_GOODOVERLOAD: return "UA_STATUSCODE_GOODOVERLOAD";
	case UA_STATUSCODE_GOODCLAMPED: return "UA_STATUSCODE_GOODCLAMPED";
	case UA_STATUSCODE_BADNOCOMMUNICATION: return "UA_STATUSCODE_BADNOCOMMUNICATION";
	case UA_STATUSCODE_BADWAITINGFORINITIALDATA: return "UA_STATUSCODE_BADWAITINGFORINITIALDATA";
	case UA_STATUSCODE_BADNODEIDINVALID: return "UA_STATUSCODE_BADNODEIDINVALID";
	case UA_STATUSCODE_BADNODEIDUNKNOWN: return "UA_STATUSCODE_BADNODEIDUNKNOWN";
	case UA_STATUSCODE_BADATTRIBUTEIDINVALID: return "UA_STATUSCODE_BADATTRIBUTEIDINVALID";
	case UA_STATUSCODE_BADINDEXRANGEINVALID: return "UA_STATUSCODE_BADINDEXRANGEINVALID";
	case UA_STATUSCODE_BADINDEXRANGENODATA: return "UA_STATUSCODE_BADINDEXRANGENODATA";
	case UA_STATUSCODE_BADDATAENCODINGINVALID: return "UA_STATUSCODE_BADDATAENCODINGINVALID";
	case UA_STATUSCODE_BADDATAENCODINGUNSUPPORTED: return "UA_STATUSCODE_BADDATAENCODINGUNSUPPORTED";
	case UA_STATUSCODE_BADNOTREADABLE: return "UA_STATUSCODE_BADNOTREADABLE";
	case UA_STATUSCODE_BADNOTWRITABLE: return "UA_STATUSCODE_BADNOTWRITABLE";
	case UA_STATUSCODE_BADOUTOFRANGE: return "UA_STATUSCODE_BADOUTOFRANGE";
	case UA_STATUSCODE_BADNOTSUPPORTED: return "UA_STATUSCODE_BADNOTSUPPORTED";
	case UA_STATUSCODE_BADNOTFOUND: return "UA_STATUSCODE_BADNOTFOUND";
	case UA_STATUSCODE_BADOBJECTDELETED: return "UA_STATUSCODE_BADOBJECTDELETED";
	case UA_STATUSCODE_BADNOTIMPLEMENTED: return "UA_STATUSCODE_BADNOTIMPLEMENTED";
	case UA_STATUSCODE_BADMONITORINGMODEINVALID: return "UA_STATUSCODE_BADMONITORINGMODEINVALID";
	case UA_STATUSCODE_BADMONITOREDITEMIDINVALID: return "UA_STATUSCODE_BADMONITOREDITEMIDINVALID";
	case UA_STATUSCODE_BADMONITOREDITEMFILTERINVALID: return "UA_STATUSCODE_BADMONITOREDITEMFILTERINVALID";
	case UA_STATUSCODE_BADMONITOREDITEMFILTERUNSUPPORTED: return "UA_STATUSCODE_BADMONITOREDITEMFILTERUNSUPPORTED";
	case UA_STATUSCODE_BADFILTERNOTALLOWED: return "UA_STATUSCODE_BADFILTERNOTALLOWED";
	case UA_STATUSCODE_BADSTRUCTUREMISSING: return "UA_STATUSCODE_BADSTRUCTUREMISSING";
	case UA_STATUSCODE_BADEVENTFILTERINVALID: return "UA_STATUSCODE_BADEVENTFILTERINVALID";
	case UA_STATUSCODE_BADCONTENTFILTERINVALID: return "UA_STATUSCODE_BADCONTENTFILTERINVALID";
	case UA_STATUSCODE_BADFILTEROPERATORINVALID: return "UA_STATUSCODE_BADFILTEROPERATORINVALID";
	case UA_STATUSCODE_BADFILTEROPERATORUNSUPPORTED: return "UA_STATUSCODE_BADFILTEROPERATORUNSUPPORTED";
	case UA_STATUSCODE_BADFILTEROPERANDCOUNTMISMATCH: return "UA_STATUSCODE_BADFILTEROPERANDCOUNTMISMATCH";
	case UA_STATUSCODE_BADFILTEROPERANDINVALID: return "UA_STATUSCODE_BADFILTEROPERANDINVALID";
	case UA_STATUSCODE_BADFILTERELEMENTINVALID: return "UA_STATUSCODE_BADFILTERELEMENTINVALID";
	case UA_STATUSCODE_BADFILTERLITERALINVALID: return "UA_STATUSCODE_BADFILTERLITERALINVALID";
	case UA_STATUSCODE_BADCONTINUATIONPOINTINVALID: return "UA_STATUSCODE_BADCONTINUATIONPOINTINVALID";
	case UA_STATUSCODE_BADNOCONTINUATIONPOINTS: return "UA_STATUSCODE_BADNOCONTINUATIONPOINTS";
	case UA_STATUSCODE_BADREFERENCETYPEIDINVALID: return "UA_STATUSCODE_BADREFERENCETYPEIDINVALID";
	case UA_STATUSCODE_BADBROWSEDIRECTIONINVALID: return "UA_STATUSCODE_BADBROWSEDIRECTIONINVALID";
	case UA_STATUSCODE_BADNODENOTINVIEW: return "UA_STATUSCODE_BADNODENOTINVIEW";
	case UA_STATUSCODE_BADSERVERURIINVALID: return "UA_STATUSCODE_BADSERVERURIINVALID";
	case UA_STATUSCODE_BADSERVERNAMEMISSING: return "UA_STATUSCODE_BADSERVERNAMEMISSING";
	case UA_STATUSCODE_BADDISCOVERYURLMISSING: return "UA_STATUSCODE_BADDISCOVERYURLMISSING";
	case UA_STATUSCODE_BADSEMPAHOREFILEMISSING: return "UA_STATUSCODE_BADSEMPAHOREFILEMISSING";
	case UA_STATUSCODE_BADREQUESTTYPEINVALID: return "UA_STATUSCODE_BADREQUESTTYPEINVALID";
	case UA_STATUSCODE_BADSECURITYMODEREJECTED: return "UA_STATUSCODE_BADSECURITYMODEREJECTED";
	case UA_STATUSCODE_BADSECURITYPOLICYREJECTED: return "UA_STATUSCODE_BADSECURITYPOLICYREJECTED";
	case UA_STATUSCODE_BADTOOMANYSESSIONS: return "UA_STATUSCODE_BADTOOMANYSESSIONS";
	case UA_STATUSCODE_BADUSERSIGNATUREINVALID: return "UA_STATUSCODE_BADUSERSIGNATUREINVALID";
	case UA_STATUSCODE_BADAPPLICATIONSIGNATUREINVALID: return "UA_STATUSCODE_BADAPPLICATIONSIGNATUREINVALID";
	case UA_STATUSCODE_BADNOVALIDCERTIFICATES: return "UA_STATUSCODE_BADNOVALIDCERTIFICATES";
	case UA_STATUSCODE_BADIDENTITYCHANGENOTSUPPORTED: return "UA_STATUSCODE_BADIDENTITYCHANGENOTSUPPORTED";
	case UA_STATUSCODE_BADREQUESTCANCELLEDBYREQUEST: return "UA_STATUSCODE_BADREQUESTCANCELLEDBYREQUEST";
	case UA_STATUSCODE_BADPARENTNODEIDINVALID: return "UA_STATUSCODE_BADPARENTNODEIDINVALID";
	case UA_STATUSCODE_BADREFERENCENOTALLOWED: return "UA_STATUSCODE_BADREFERENCENOTALLOWED";
	case UA_STATUSCODE_BADNODEIDREJECTED: return "UA_STATUSCODE_BADNODEIDREJECTED";
	case UA_STATUSCODE_BADNODEIDEXISTS: return "UA_STATUSCODE_BADNODEIDEXISTS";
	case UA_STATUSCODE_BADNODECLASSINVALID: return "UA_STATUSCODE_BADNODECLASSINVALID";
	case UA_STATUSCODE_BADBROWSENAMEINVALID: return "UA_STATUSCODE_BADBROWSENAMEINVALID";
	case UA_STATUSCODE_BADBROWSENAMEDUPLICATED: return "UA_STATUSCODE_BADBROWSENAMEDUPLICATED";
	case UA_STATUSCODE_BADNODEATTRIBUTESINVALID: return "UA_STATUSCODE_BADNODEATTRIBUTESINVALID";
	case UA_STATUSCODE_BADTYPEDEFINITIONINVALID: return "UA_STATUSCODE_BADTYPEDEFINITIONINVALID";
	case UA_STATUSCODE_BADSOURCENODEIDINVALID: return "UA_STATUSCODE_BADSOURCENODEIDINVALID";
	case UA_STATUSCODE_BADTARGETNODEIDINVALID: return "UA_STATUSCODE_BADTARGETNODEIDINVALID";
	case UA_STATUSCODE_BADDUPLICATEREFERENCENOTALLOWED: return "UA_STATUSCODE_BADDUPLICATEREFERENCENOTALLOWED";
	case UA_STATUSCODE_BADINVALIDSELFREFERENCE: return "UA_STATUSCODE_BADINVALIDSELFREFERENCE";
	case UA_STATUSCODE_BADREFERENCELOCALONLY: return "UA_STATUSCODE_BADREFERENCELOCALONLY";
	case UA_STATUSCODE_BADNODELETERIGHTS: return "UA_STATUSCODE_BADNODELETERIGHTS";
	case UA_STATUSCODE_UNCERTAINREFERENCENOTDELETED: return "UA_STATUSCODE_UNCERTAINREFERENCENOTDELETED";
	case UA_STATUSCODE_BADSERVERINDEXINVALID: return "UA_STATUSCODE_BADSERVERINDEXINVALID";
	case UA_STATUSCODE_BADVIEWIDUNKNOWN: return "UA_STATUSCODE_BADVIEWIDUNKNOWN";
	case UA_STATUSCODE_BADVIEWTIMESTAMPINVALID: return "UA_STATUSCODE_BADVIEWTIMESTAMPINVALID";
	case UA_STATUSCODE_BADVIEWPARAMETERMISMATCH: return "UA_STATUSCODE_BADVIEWPARAMETERMISMATCH";
	case UA_STATUSCODE_BADVIEWVERSIONINVALID: return "UA_STATUSCODE_BADVIEWVERSIONINVALID";
	case UA_STATUSCODE_UNCERTAINNOTALLNODESAVAILABLE: return "UA_STATUSCODE_UNCERTAINNOTALLNODESAVAILABLE";
	case UA_STATUSCODE_GOODRESULTSMAYBEINCOMPLETE: return "UA_STATUSCODE_GOODRESULTSMAYBEINCOMPLETE";
	case UA_STATUSCODE_BADNOTTYPEDEFINITION: return "UA_STATUSCODE_BADNOTTYPEDEFINITION";
	case UA_STATUSCODE_UNCERTAINREFERENCEOUTOFSERVER: return "UA_STATUSCODE_UNCERTAINREFERENCEOUTOFSERVER";
	case UA_STATUSCODE_BADTOOMANYMATCHES: return "UA_STATUSCODE_BADTOOMANYMATCHES";
	case UA_STATUSCODE_BADQUERYTOOCOMPLEX: return "UA_STATUSCODE_BADQUERYTOOCOMPLEX";
	case UA_STATUSCODE_BADNOMATCH: return "UA_STATUSCODE_BADNOMATCH";
	case UA_STATUSCODE_BADMAXAGEINVALID: return "UA_STATUSCODE_BADMAXAGEINVALID";
	case UA_STATUSCODE_BADHISTORYOPERATIONINVALID: return "UA_STATUSCODE_BADHISTORYOPERATIONINVALID";
	case UA_STATUSCODE_BADHISTORYOPERATIONUNSUPPORTED: return "UA_STATUSCODE_BADHISTORYOPERATIONUNSUPPORTED";
	case UA_STATUSCODE_BADINVALIDTIMESTAMPARGUMENT: return "UA_STATUSCODE_BADINVALIDTIMESTAMPARGUMENT";
	case UA_STATUSCODE_BADWRITENOTSUPPORTED: return "UA_STATUSCODE_BADWRITENOTSUPPORTED";
	case UA_STATUSCODE_BADTYPEMISMATCH: return "UA_STATUSCODE_BADTYPEMISMATCH";
	case UA_STATUSCODE_BADMETHODINVALID: return "UA_STATUSCODE_BADMETHODINVALID";
	case UA_STATUSCODE_BADARGUMENTSMISSING: return "UA_STATUSCODE_BADARGUMENTSMISSING";
	case UA_STATUSCODE_BADTOOMANYSUBSCRIPTIONS: return "UA_STATUSCODE_BADTOOMANYSUBSCRIPTIONS";
	case UA_STATUSCODE_BADTOOMANYPUBLISHREQUESTS: return "UA_STATUSCODE_BADTOOMANYPUBLISHREQUESTS";
	case UA_STATUSCODE_BADNOSUBSCRIPTION: return "UA_STATUSCODE_BADNOSUBSCRIPTION";
	case UA_STATUSCODE_BADSEQUENCENUMBERUNKNOWN: return "UA_STATUSCODE_BADSEQUENCENUMBERUNKNOWN";
	case UA_STATUSCODE_BADMESSAGENOTAVAILABLE: return "UA_STATUSCODE_BADMESSAGENOTAVAILABLE";
	case UA_STATUSCODE_BADINSUFFICIENTCLIENTPROFILE: return "UA_STATUSCODE_BADINSUFFICIENTCLIENTPROFILE";
	case UA_STATUSCODE_BADSTATENOTACTIVE: return "UA_STATUSCODE_BADSTATENOTACTIVE";
	case UA_STATUSCODE_BADTCPSERVERTOOBUSY: return "UA_STATUSCODE_BADTCPSERVERTOOBUSY";
	case UA_STATUSCODE_BADTCPMESSAGETYPEINVALID: return "UA_STATUSCODE_BADTCPMESSAGETYPEINVALID";
	case UA_STATUSCODE_BADTCPSECURECHANNELUNKNOWN: return "UA_STATUSCODE_BADTCPSECURECHANNELUNKNOWN";
	case UA_STATUSCODE_BADTCPMESSAGETOOLARGE: return "UA_STATUSCODE_BADTCPMESSAGETOOLARGE";
	case UA_STATUSCODE_BADTCPNOTENOUGHRESOURCES: return "UA_STATUSCODE_BADTCPNOTENOUGHRESOURCES";
	case UA_STATUSCODE_BADTCPINTERNALERROR: return "UA_STATUSCODE_BADTCPINTERNALERROR";
	case UA_STATUSCODE_BADTCPENDPOINTURLINVALID: return "UA_STATUSCODE_BADTCPENDPOINTURLINVALID";
	case UA_STATUSCODE_BADREQUESTINTERRUPTED: return "UA_STATUSCODE_BADREQUESTINTERRUPTED";
	case UA_STATUSCODE_BADREQUESTTIMEOUT: return "UA_STATUSCODE_BADREQUESTTIMEOUT";
	case UA_STATUSCODE_BADSECURECHANNELCLOSED: return "UA_STATUSCODE_BADSECURECHANNELCLOSED";
	case UA_STATUSCODE_BADSECURECHANNELTOKENUNKNOWN: return "UA_STATUSCODE_BADSECURECHANNELTOKENUNKNOWN";
	case UA_STATUSCODE_BADSEQUENCENUMBERINVALID: return "UA_STATUSCODE_BADSEQUENCENUMBERINVALID";
	case UA_STATUSCODE_BADPROTOCOLVERSIONUNSUPPORTED: return "UA_STATUSCODE_BADPROTOCOLVERSIONUNSUPPORTED";
	case UA_STATUSCODE_BADCONFIGURATIONERROR: return "UA_STATUSCODE_BADCONFIGURATIONERROR";
	case UA_STATUSCODE_BADNOTCONNECTED: return "UA_STATUSCODE_BADNOTCONNECTED";
	case UA_STATUSCODE_BADDEVICEFAILURE: return "UA_STATUSCODE_BADDEVICEFAILURE";
	case UA_STATUSCODE_BADSENSORFAILURE: return "UA_STATUSCODE_BADSENSORFAILURE";
	case UA_STATUSCODE_BADOUTOFSERVICE: return "UA_STATUSCODE_BADOUTOFSERVICE";
	case UA_STATUSCODE_BADDEADBANDFILTERINVALID: return "UA_STATUSCODE_BADDEADBANDFILTERINVALID";
	case UA_STATUSCODE_UNCERTAINNOCOMMUNICATIONLASTUSABLEVALUE: return "UA_STATUSCODE_UNCERTAINNOCOMMUNICATIONLASTUSABLEVALUE";
	case UA_STATUSCODE_UNCERTAINLASTUSABLEVALUE: return "UA_STATUSCODE_UNCERTAINLASTUSABLEVALUE";
	case UA_STATUSCODE_UNCERTAINSUBSTITUTEVALUE: return "UA_STATUSCODE_UNCERTAINSUBSTITUTEVALUE";
	case UA_STATUSCODE_UNCERTAININITIALVALUE: return "UA_STATUSCODE_UNCERTAININITIALVALUE";
	case UA_STATUSCODE_UNCERTAINSENSORNOTACCURATE: return "UA_STATUSCODE_UNCERTAINSENSORNOTACCURATE";
	case UA_STATUSCODE_UNCERTAINENGINEERINGUNITSEXCEEDED: return "UA_STATUSCODE_UNCERTAINENGINEERINGUNITSEXCEEDED";
	case UA_STATUSCODE_UNCERTAINSUBNORMAL: return "UA_STATUSCODE_UNCERTAINSUBNORMAL";
	case UA_STATUSCODE_GOODLOCALOVERRIDE: return "UA_STATUSCODE_GOODLOCALOVERRIDE";
	case UA_STATUSCODE_BADREFRESHINPROGRESS: return "UA_STATUSCODE_BADREFRESHINPROGRESS";
	case UA_STATUSCODE_BADCONDITIONALREADYDISABLED: return "UA_STATUSCODE_BADCONDITIONALREADYDISABLED";
	case UA_STATUSCODE_BADCONDITIONALREADYENABLED: return "UA_STATUSCODE_BADCONDITIONALREADYENABLED";
	case UA_STATUSCODE_BADCONDITIONDISABLED: return "UA_STATUSCODE_BADCONDITIONDISABLED";
	case UA_STATUSCODE_BADEVENTIDUNKNOWN: return "UA_STATUSCODE_BADEVENTIDUNKNOWN";
	case UA_STATUSCODE_BADEVENTNOTACKNOWLEDGEABLE: return "UA_STATUSCODE_BADEVENTNOTACKNOWLEDGEABLE";
	case UA_STATUSCODE_BADDIALOGNOTACTIVE: return "UA_STATUSCODE_BADDIALOGNOTACTIVE";
	case UA_STATUSCODE_BADDIALOGRESPONSEINVALID: return "UA_STATUSCODE_BADDIALOGRESPONSEINVALID";
	case UA_STATUSCODE_BADCONDITIONBRANCHALREADYACKED: return "UA_STATUSCODE_BADCONDITIONBRANCHALREADYACKED";
	case UA_STATUSCODE_BADCONDITIONBRANCHALREADYCONFIRMED: return "UA_STATUSCODE_BADCONDITIONBRANCHALREADYCONFIRMED";
	case UA_STATUSCODE_BADCONDITIONALREADYSHELVED: return "UA_STATUSCODE_BADCONDITIONALREADYSHELVED";
	case UA_STATUSCODE_BADCONDITIONNOTSHELVED: return "UA_STATUSCODE_BADCONDITIONNOTSHELVED";
	case UA_STATUSCODE_BADSHELVINGTIMEOUTOFRANGE: return "UA_STATUSCODE_BADSHELVINGTIMEOUTOFRANGE";
	case UA_STATUSCODE_BADNODATA: return "UA_STATUSCODE_BADNODATA";
	case UA_STATUSCODE_BADBOUNDNOTFOUND: return "UA_STATUSCODE_BADBOUNDNOTFOUND";
	case UA_STATUSCODE_BADBOUNDNOTSUPPORTED: return "UA_STATUSCODE_BADBOUNDNOTSUPPORTED";
	case UA_STATUSCODE_BADDATALOST: return "UA_STATUSCODE_BADDATALOST";
	case UA_STATUSCODE_BADDATAUNAVAILABLE: return "UA_STATUSCODE_BADDATAUNAVAILABLE";
	case UA_STATUSCODE_BADENTRYEXISTS: return "UA_STATUSCODE_BADENTRYEXISTS";
	case UA_STATUSCODE_BADNOENTRYEXISTS: return "UA_STATUSCODE_BADNOENTRYEXISTS";
	case UA_STATUSCODE_BADTIMESTAMPNOTSUPPORTED: return "UA_STATUSCODE_BADTIMESTAMPNOTSUPPORTED";
	case UA_STATUSCODE_GOODENTRYINSERTED: return "UA_STATUSCODE_GOODENTRYINSERTED";
	case UA_STATUSCODE_GOODENTRYREPLACED: return "UA_STATUSCODE_GOODENTRYREPLACED";
	case UA_STATUSCODE_UNCERTAINDATASUBNORMAL: return "UA_STATUSCODE_UNCERTAINDATASUBNORMAL";
	case UA_STATUSCODE_GOODNODATA: return "UA_STATUSCODE_GOODNODATA";
	case UA_STATUSCODE_GOODMOREDATA: return "UA_STATUSCODE_GOODMOREDATA";
	case UA_STATUSCODE_BADAGGREGATELISTMISMATCH: return "UA_STATUSCODE_BADAGGREGATELISTMISMATCH";
	case UA_STATUSCODE_BADAGGREGATENOTSUPPORTED: return "UA_STATUSCODE_BADAGGREGATENOTSUPPORTED";
	case UA_STATUSCODE_BADAGGREGATEINVALIDINPUTS: return "UA_STATUSCODE_BADAGGREGATEINVALIDINPUTS";
	case UA_STATUSCODE_BADAGGREGATECONFIGURATIONREJECTED: return "UA_STATUSCODE_BADAGGREGATECONFIGURATIONREJECTED";
	case UA_STATUSCODE_GOODDATAIGNORED: return "UA_STATUSCODE_GOODDATAIGNORED";
	case UA_STATUSCODE_GOODCOMMUNICATIONEVENT: return "UA_STATUSCODE_GOODCOMMUNICATIONEVENT";
	case UA_STATUSCODE_GOODSHUTDOWNEVENT: return "UA_STATUSCODE_GOODSHUTDOWNEVENT";
	case UA_STATUSCODE_GOODCALLAGAIN: return "UA_STATUSCODE_GOODCALLAGAIN";
	case UA_STATUSCODE_GOODNONCRITICALTIMEOUT: return "UA_STATUSCODE_GOODNONCRITICALTIMEOUT";
	case UA_STATUSCODE_BADINVALIDARGUMENT: return "UA_STATUSCODE_BADINVALIDARGUMENT";
	case UA_STATUSCODE_BADCONNECTIONREJECTED: return "UA_STATUSCODE_BADCONNECTIONREJECTED";
	case UA_STATUSCODE_BADDISCONNECT: return "UA_STATUSCODE_BADDISCONNECT";
	case UA_STATUSCODE_BADCONNECTIONCLOSED: return "UA_STATUSCODE_BADCONNECTIONCLOSED";
	case UA_STATUSCODE_BADINVALIDSTATE: return "UA_STATUSCODE_BADINVALIDSTATE";
	case UA_STATUSCODE_BADENDOFSTREAM: return "UA_STATUSCODE_BADENDOFSTREAM";
	case UA_STATUSCODE_BADNODATAAVAILABLE: return "UA_STATUSCODE_BADNODATAAVAILABLE";
	case UA_STATUSCODE_BADWAITINGFORRESPONSE: return "UA_STATUSCODE_BADWAITINGFORRESPONSE";
	case UA_STATUSCODE_BADOPERATIONABANDONED: return "UA_STATUSCODE_BADOPERATIONABANDONED";
	case UA_STATUSCODE_BADEXPECTEDSTREAMTOBLOCK: return "UA_STATUSCODE_BADEXPECTEDSTREAMTOBLOCK";
	case UA_STATUSCODE_BADWOULDBLOCK: return "UA_STATUSCODE_BADWOULDBLOCK";
	case UA_STATUSCODE_BADSYNTAXERROR: return "UA_STATUSCODE_BADSYNTAXERROR";
   }
}

int main(int argc, char** argv) {
    signal(SIGINT, stopHandler);
    signal(SIGTERM, stopHandler);
    
    UA_Server *server = UA_Server_new();
    UA_ServerConfig_setDefault(UA_Server_getConfig(server));
    UA_StatusCode retval;
    /* create nodes from nodeset */
    
	retval = namespace_di_generated(server);
	if(retval != UA_STATUSCODE_GOOD) {
    		UA_LOG_ERROR(UA_Log_Stdout, UA_LOGCATEGORY_SERVER,
                 	"Adding the DI namespace failed. Please check previous error output.");
    		UA_Server_delete(server);
    		//return (int)UA_STATUSCODE_BADUNEXPECTEDERROR;
	}

	retval |= namespace_Robotics_generated(server);
	if(retval != UA_STATUSCODE_GOOD) {
    		UA_LOG_ERROR(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "Could not add the Robotics nodeset. "
        	"Check previous output for any error.");
        	retval = UA_STATUSCODE_BADUNEXPECTEDERROR;
	}

	UA_Server_run(server, &running);
    
/*
    UA_StatusCode mountServerStatus = namespace_Robotics_generated(server);
    if(mountServerStatus != UA_STATUSCODE_GOOD) {
        UA_LOG_ERROR(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "Could not add the Robotics nodeset. "
        "Check previous output for any error.");
        retval = UA_STATUSCODE_BADUNEXPECTEDERROR;
    } else {
        //Do some additional stuff with the nodes
        this will just get the namespace index, since it is already added to the server
        UA_UInt16 nsIdx = UA_Server_addNamespace(server, "http://opcfoundation.org/UA/Robotics/");
        UA_NodeId testInstanceId = UA_NODEID_NUMERIC(nsIdx, UA_FOO_FLTID_APE);
        UA_LOG_INFO(UA_Log_Stdout, UA_LOGCATEGORY_SERVER, "The Ape has ns=%d;id=%d",
                    testInstanceId.namespaceIndex, testInstanceId.identifier.numeric);
        retval = UA_Server_run(server, &running);
    }
    printf("%s",getErrorName(mountServerStatus)); 
*/
    UA_Server_delete(server);
    return retval == UA_STATUSCODE_GOOD ? EXIT_SUCCESS : EXIT_FAILURE;
}
